[project]
authors = ["Elouen_Corvest <elouen.corvest@rwth-aachen.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
matplotlib = ">=3.10.7, <4"
pandas = ">=2.3.3, <3"
