[workspace]
authors = ["ElouenCorvest <elouen2000@gmail.com>"]
channels = ["conda-forge"]
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
reportlab = "*"
svglib = ">=1.6.0,<2"

[pypi-dependencies]
pandas = ">=3.0.0, <4"
jinja2 = ">=3.1.6, <4"
xlrd = ">=2.0.2, <3"
matplotlib = ">=3.10.8, <4"
requests = ">=2.32.5, <3"
rwth-cd-colors = ">=0.1.1, <0.2"
rwthcolors = ">=0.3.0, <0.4"



